# Generated by Django 5.2.5 on 2025-08-28 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('receipts', '0002_rename_description_receipt_remark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='party_name',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='transport_name',
        ),
        migrations.AddField(
            model_name='receipt',
            name='party_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts_as_party', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='transport_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts_as_transport', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='delivery_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts_as_delivery', to='accounts.account'),
        ),
    ]
