# Generated by Django 5.2.5 on 2025-09-17 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_journalentry_voucher_type'),
        ('receipts', '0003_remove_receipt_party_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='journals.journalentry'),
        ),
    ]
