# Generated by Django 5.2.5 on 2025-09-01 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentryline',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='journalentryline',
            name='account',
        ),
        migrations.DeleteModel(
            name='JournalEntry',
        ),
        migrations.DeleteModel(
            name='JournalEntryLine',
        ),
    ]
