# Generated by Django 5.2.5 on 2025-09-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_journalentryline_journal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_system',
            field=models.BooleanField(default=False, help_text='True if system-defined and should not be deleted'),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='is_system',
            field=models.BooleanField(default=False, help_text='True if system-defined and should not be deleted'),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='normal_balance',
            field=models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], default='D', help_text='Normal balance side for this account type', max_length=1),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
