# Generated by Django 5.2.5 on 2025-09-14 19:30

from django.db import migrations


def create_delivery_accounts(apps, schema_editor):
    AccountType = apps.get_model('accounts', 'AccountType')
    Account = apps.get_model('accounts', 'Account')

    try:
        liability_type = AccountType.objects.get(code="LIAB")
        ap_account = Account.objects.get(code="1001")  # Accounts Payable
    except (AccountType.DoesNotExist, Account.DoesNotExist):
        return  # skip if base accounts not found

    Account.objects.get_or_create(
        code="1200",
        defaults={
            "name": "Delivery Accounts",
            "account_type": liability_type,
            "parent": ap_account,
            "is_system": True,
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_init_system_accounts'),  # adjust to your last migration name
    ]

    operations = [
        migrations.RunPython(create_delivery_accounts),
    ]
