# Generated by Django 5.2.5 on 2025-09-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='voucher_no',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
    ]
