# Generated by Django 5.2.5 on 2025-09-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_alter_journalentry_voucher_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='voucher_type',
            field=models.CharField(choices=[('JV', 'Journal Voucher'), ('RV', 'Receipt Voucher'), ('PV', 'Payment Voucher'), ('CN', 'Contra Voucher'), ('DN', 'Debit Note'), ('CNV', 'Credit Note')], default='JV', max_length=10),
        ),
    ]
